Support ldap groups
indexima-dev/ansible-indexima-install pull request #48
Opened 2021-02-23 11:29 UTC by jnduwamu

- Added variables for LDAP authentication
- Added a new scenario for testing LDAP

2021-02-23 12:09 UTC, indexima-team requested changes

2021-02-23 12:09 UTC, indexima-team commented on molecule/docker-auth/molecule.yml
> +        auth_password: ${AUTH_PASSWORD}
Need consistent variable name: LDAP_USERNAME and LDAP_PASSWORD

2021-02-23 12:09 UTC, indexima-team commented on molecule/docker-auth/molecule.yml
> +        ldap_group_membershipkey: ${LDAP_GROUP_MEMBERSHIPKEY}
Don't put these in env variable. It is not sensible data and it is tested in verify.yml so it needs to be set explicitly

2021-02-23 12:09 UTC, indexima-team commented on molecule/docker-auth/molecule.yml
> +        ha: 0
remove all these (except warehouse)

2021-02-23 12:09 UTC, indexima-team commented on tasks/config_visualdoop.yaml
> +    - "{{ ldap| bool }} == 'true'"
```ldap |bool```
is enough

2021-02-23 12:09 UTC, indexima-team commented on molecule/docker-auth/molecule.yml
> +    - destroy
This can be deleted

2021-02-23 12:18 UTC, indexima-team commented on molecule/docker-auth/molecule.yml
> +        auth_password: ${AUTH_PASSWORD}
Nvm actually AUTH is ok for future tests

2021-02-24 12:16 UTC, indexima-team commented on molecule/docker-auth/molecule.yml
> +        auth_password: ${AUTH_PASSWORD}
up

2021-02-24 12:38 UTC, jnduwamu commented on molecule/docker-auth/molecule.yml
> +        auth_password: ${AUTH_PASSWORD}
You commented on this yesterday saying the name AUTH is actually ok for future tests

2021-02-24 14:51 UTC, indexima-team approved these changes

2021-02-24 15:03 UTC, merged