Refacto prerequisites
indexima-dev/ansible-indexima-install pull request #6
Opened 2020-10-06 12:16 UTC by jnduwamu

The files debian.yml and centos.yml in the task directory were merged into os_prerequisites.yml file to prevent repetitive code
The task that install unzip is modified to be installed whatever the os by using the following module : 
`- name: Install unzip
  package:
    name: unzip
    state: present`

Since the name of the java package is different on debian os and on centos we'll install it accordingly on the two systems by using the condition `when`

2020-10-06 18:59 UTC, NicoGGG requested changes

2020-10-06 18:59 UTC, NicoGGG commented on tasks/os_prerequisites.yaml
> +    mode: '0755'
```suggestion
```

2020-10-06 18:59 UTC, NicoGGG commented on tasks/os_prerequisites.yaml
>    file:
Remove this task. This is done in install_prep.yml

2020-10-07 08:16 UTC, jnduwamu commented on tasks/os_prerequisites.yaml
> +    mode: '0755'
Done

2020-10-07 08:16 UTC, jnduwamu commented
Done

2020-10-07 08:18 UTC, jnduwamu commented
Conflict handled

2020-10-07 08:21 UTC, NicoGGG approved these changes

2020-10-07 08:50 UTC, merged